sudo: required
services:
  - docker

before_install:
  - docker build -t purporz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true purporz/docker-react npm run test

language: generic